/*
 * generated by Xtext 2.10.0
 */
package software.amazon.ionxtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IonStandaloneSetup extends IonStandaloneSetupGenerated {

	def static void doSetup() {
		new IonStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
